[2019-09-05 01:30:33,372][DEBUG][__main__.py][<module>][ 14]: running __main__
[2019-09-05 01:30:33,372][DEBUG][adble.py][_connect][ 41]: 正在连接模拟器127.0.0.1:62001
[2019-09-05 01:30:34,403][DEBUG][adble.py][_getDevice][101]: 获取连接的设备信息
[2019-09-05 01:30:34,435][DEBUG][adble.py][_getDevice][106]: 已连接设备 []
[2019-09-05 01:30:34,435][DEBUG][adble.py][__init__][ 36]: 未连接设备
